### PR TITLE
Migrated to null-safety

### PR DESCRIPTION
**Pull request by aloysiousBenoy**
Migrated to null safety and bumped up dependencies.  
Passes static analysis

### CODE REVIEW

**Review by ecdundar — COMMENTED** [review]
Could you please publish this pull request?

**Comment by Eittipat** [comment]
I have to test this before publishing to pubdev.
Maybe this weekend.

**Comment by jeroen-meijer** [comment]
Checking if this is still on your radar after all this time 👀

**Comment by Eittipat** [comment]
@jeroen-meijer You still need this package?

**Pull request merged**
